# Generated by Django 4.1.2 on 2022-11-11 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_alter_teacher_managers"),
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "duration",
                    models.DurationField(
                        choices=[
                            (datetime.timedelta(seconds=900), "15min"),
                            (datetime.timedelta(seconds=1800), "30min"),
                            (datetime.timedelta(seconds=2700), "45min"),
                            (datetime.timedelta(seconds=3600), "1h"),
                        ],
                        default=datetime.timedelta(seconds=900),
                        verbose_name="duration",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(default=False, verbose_name="is disabled"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation type",
                "verbose_name_plural": "Reservation types",
            },
        ),
    ]
