# Generated by Django 4.1.2 on 2022-11-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_reservation_reservationslot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultation",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationslot",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Reservation slot",
                "verbose_name_plural": "Reservation slots",
            },
        ),
    ]
