# Generated by Django 4.1.2 on 2022-12-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_alter_teacher_managers"),
        ("students", "0004_student_major"),
        ("consultations", "0005_reservation_was_absent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_reservation",
                to="students.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers_reservation",
                to="teachers.teacher",
                verbose_name="teacher",
            ),
        ),
    ]
