# Generated by Django 4.1.2 on 2022-10-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="student",
        ),
    ]
