# Generated by Django 4.1.2 on 2022-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Major"),
        ),
    ]
