# Generated by Django 4.0 on 2022-10-15 16:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('degrees', models.CharField(blank=True, max_length=50, null=True, verbose_name='degrees')),
                ('name_display', models.CharField(blank=True, help_text='Leave this blank if you want the default way of showing the name (degrees, first name, last name)', max_length=255, null=True, verbose_name='name display')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
