# Generated by Django 4.1.2 on 2023-01-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers_user_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="verified at"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="register_token",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Register token"
            ),
        ),
    ]
