# Generated by Django 4.1.2 on 2022-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Year of study"
            ),
        ),
    ]
