# Generated by Django 4.1.2 on 2022-10-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_year"),
        ("school", "0002_alter_major_name")
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="school.major",
                verbose_name="Students Major",
            ),
        ),
    ]
